export enum EnumRoutes {
  HOME = '/home',
  ONBOARDING = '/onboarding',
  SEARCH = '/search',
  SEARCH_DETAIL = '/search/:searchType',
  FRIENDS = '/friends',
  PROFILE = '/profile',
  PROFILE_SETTINGS = '/profile/settings',
  PROFILE_GAMES = '/profile/games',
  PROFILE_TICKETS = '/profile/tickets',
  PROFILE_TICKET_DETAIL = '/profile/tickets/:ticketId',
  PROFILE_SUPPORT = '/profile/support',
  PROFILE_PRIVACY = '/profile/privacy',
  PROFILE_INFO_REALLIFE = '/profile/info/realLife',
  PROFILE_INFO_ONLINE = '/profile/info/online',
  NOTIFICATIONS = '/notifications',
}